### ISSUE TITLE
refresh_token i am getting Forbidden 403

### ISSUE THREAD

**Issue by gastoncs** [gesdinet/JWTRefreshTokenBundle#107]
Hi,

I am getting forbidden while doing the refresh_token

`curl -X POST http://localhost:8083/api/token/refresh --data refresh_token=9be6a1654513bab76c3c0da96c4cb8c01abaad8d4a3b53a7f1e3ebe89caf034fbeb60f562876216720b173e01649a362f3711233f994aa11a722a82fff15d399`

routing.yml
`gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
`

security.yml
`
    firewalls:
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        - { path: ^/api/token/refresh, role: IS_AUTHENTICATED_ANONYMOUSLY }
`

config.yml
`gesdinet_jwt_refresh_token:
    user_provider: fos_user.user_provider.username_email
    ttl_update: false
    firewall: api
`

I am using the refresh token.

Thanks

**Comment by shakaran** [comment]
@gastoncs, nobody answered you in seven years. Sorry.

**The status code is the clue.** A 403 is not an authentication failure — that would be a 401, which is what this bundle returns when a refresh token is missing, unknown or expired. A 403 means the request got past authentication and was then refused by `access_control`. So whatever was wrong, it was not the refresh token.

In the configuration you pasted, the access rule appears indented under `firewalls:`:

```yaml
firewalls:
    refresh:
        pattern:  ^/api/token/refresh
        stateless: true
        anonymous: true

    - { path: ^/api/token/refresh, role: IS_AUTHENTICATED_ANONYMOUSLY }
```

If that is where it really was rather than an artefact of pasting, it is the whole answer: `access_control` is a sibling of `firewalls`, not a child, so the rule never applied and a broader one denied the request. The same mistake is #275. Worth checking too that it said `roles`, plural — `role` is not an option there.

**None of that configuration exists any more**, so there is nothing to salvage from it. `user_provider`, `firewall`, the `_controller` default and `anonymous` are all gone, and the refresh endpoint is a firewall authenticator rather than a controller. `firewall` in particular was later deprecated without replacement, which tells you how much it was doing.

What it looks like now:

```yaml
# config/routes.yaml
api_refresh_token:
    path: /api/token/refresh

# config/packages/security.yaml
security:
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

    access_control:
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
```

`PUBLIC_ACCESS` replaces `IS_AUTHENTICATED_ANONYMOUSLY`, one firewall replaces two, and the route needs no controller — the firewall answers the path before one would be reached.

Your `curl` was fine, for what it is worth: a form-encoded `refresh_token` is read by the request parameter extractor.

Closing this.
