### ISSUE TITLE
Class gesdinet.jwtrefreshtoken does not exist.

### ISSUE THREAD

**Issue by maciejkosiarski** [gesdinet/JWTRefreshTokenBundle#116]
I get refresh token but when I call jwt refresh path response is 500 (Class gesdinet.jwtrefreshtoken does not exist. (500 Internal Server Error)) 
composer.json
```json
`"require"` : {
		"php" : ">=7.1",
		"symfony/symfony" : "3.4.*",
		"doctrine/orm" : "^2.5",
		"doctrine/doctrine-bundle" : "^1.6",
		"doctrine/doctrine-cache-bundle" : "^1.3",
		....
                "lexik/jwt-authentication-bundle": "^2.4",
		"gesdinet/jwt-refresh-token-bundle": "^0.5.2"
	},`

the configuration is identical to the documentation, anyone can help?

**Comment by markitosgv** [comment]
Hi,

You must extend and configure your own entity class.

Look at this https://github.com/gesdinet/JWTRefreshTokenBundle#use-another-entity-for-refresh-tokens

**Comment by maciejkosiarski** [comment]
It isn't working, a think problem is here:

```yml
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken::refresh }
```
app can't see RefreshToken service
