### ISSUE TITLE
There is no extension able to load the configuration for "gesdinet_jwt_refresh_token" (Symfony 4)

### ISSUE THREAD

**Issue by LANSELOT** [gesdinet/JWTRefreshTokenBundle#122]
Hi. I have some problem with this bundle in Symfony 4.1.
I created file with configuration
```
# /config/packages/gesdinet_jwt_refresh_token.yaml
gesdinet_jwt_refresh_token:
    ttl: 2592000
    ttl_update: true
    user_identity_field: email
    # refresh_token_class: App\Entity\JwtRefreshToken
```
And I get an error:
There is no extension able to load the configuration for "gesdinet_jwt_refresh_token" (in /srv/www/project/config/packages/gesdinet_jwt_refresh_token.yaml).

Where am I wrong?
