### ISSUE TITLE
object_manager not recognized

### ISSUE THREAD

**Issue by stijn-at-work** [gesdinet/JWTRefreshTokenBundle#157]
unable to generate a refresh token with our second (non default) entity manager. 

error: Unable to replace alias "gesdinet.jwtrefreshtoken.object_manager" with actual definition "[entity_manager_2]".

```
config.yml

doctrine:
    orm:
        default_entity_manager: [entity_manager_1]
        entity_managers:
            entity_manager_1:
                connection: [connection_1]
                mappings:
                    ...
            entity_manager_2:
                connection: [connection_2]
                mappings:
                    ...

gesdinet_jwt_refresh_token:
    user_provider: [my_user_provider]
    object_manager: [entity_manager_2]
```

**Comment by HamHamFonFon** [comment]
Have you trying with : 
`
gesdinet_jwt_refresh_token:
    user_provider: my_user_provider
    object_manager: doctrine.orm.entity_manager_2_entity_manager
`
?

**Comment by shakaran** [comment]
Two different problems ended up here, and both now have answers. Fixed and documented in 2e025a2.

**@stijn-at-work**, `object_manager` takes a service id, and `entity_manager_2` is the name the manager is configured under, not its service. The service is `doctrine.orm.entity_manager_2_entity_manager`. That is what your error was about — Symfony could not replace the alias because nothing was registered under that id — but the message says nothing about what to write instead.

A compiler pass now says it, mirroring the one already checking the DBAL connection:

```text
The object manager service "entity_manager_2" does not exist. The "object_manager" option takes a
service id rather than the name an entity manager is configured under: an entity manager named
"foo" is the service "doctrine.orm.foo_entity_manager".
Available object managers: doctrine.orm.default_entity_manager, doctrine.orm.entity_manager_2_entity_manager
```

**@Astro-Otter-Space**, you got past that and hit the real one, which nobody answered: `doctrine:schema:update --em=custom_em` found nothing to create. Doctrine allows `auto_mapping` on only one entity manager, so the bundle's mapping is registered with that one and with no other. Pointing `object_manager` at a different manager does not move the mapping there.

It has to be declared under that manager as well:

```yaml
gesdinet_jwt_refresh_token:
    object_manager: doctrine.orm.custom_em_entity_manager

doctrine:
    orm:
        entity_managers:
            custom_em:
                connection: custom_connection
                mappings:
                    GesdinetJWTRefreshToken:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/vendor/gesdinet/jwt-refresh-token-bundle/config/doctrine'
                        prefix: 'Gesdinet\JWTRefreshTokenBundle\Entity'
```

Your own token class needs mapping under that manager too, since it is the one that gets a table. Your commented-out `#GesdinetJWTRefreshTokenBundle: ~` was the right instinct — that form no longer applies, as the mapping is not a bundle mapping any more, but declaring it explicitly is.

Both are in the README now, under the mapping section. This also covers #212, which is the same ground.

Closing this. Sorry it took six years, and that the second half of it was never addressed at all.
