### ISSUE TITLE
Symfony 6 Unable to find the controller for path "/api/token/refresh". The route is wrongly configured.

### ISSUE THREAD

**Issue by bscript-dev** [gesdinet/JWTRefreshTokenBundle#307]
In symfony 6 refresh token not working properly because it unable to find the controller. Do you have any solution for this case ?

security.yaml -> firewalls:
```
# ...
 firewalls:
        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: uusr_login
                password_path: uusr_pass
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            provider: app_user_provider
            logout:
                path: app_logout
# ...

```
router.yaml:
```

api_login:
    path: /api/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
```

**Comment by mv-developer** [comment]
You need to add provider to api_token_refresh

Ex:

api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            provider: app_user_provider
            refresh_jwt: ~

**Comment by DougHayward** [comment]
Same issue here.

**Comment by gregurco** [comment]
Same issue. Did someone got the idea how to fix it?

**Comment by andrconstruction** [comment]
Same issue on 5.4

**Comment by andrconstruction** [comment]
I has a problem with a GET request,  should be a POST

**Comment by Jayfrown** [comment]
This happens because in the latest release the authenticator only reports support for requests where the refresh token is present. A fix has been merged (just now) but has not yet been included in a release.

So sending an empty request will result in a 404, but using the route as intended (ie. sending the refresh token with the request in a manner the extractor can find it) should work as expected.

Until the next release, a dirty work-around could be to add the following to your route configuration:

```yaml
api_token_refresh:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
```

In this case, using the route as intended will still trigger the authenticator system (and not use the defined controller) but any request to the same path where the authenticator does not trigger, will end up using the controller instead of returning a 404. Just don't forget to remove the controller config when a new version is released.

See [1] and [2].

[1]: https://github.com/markitosgv/JWTRefreshTokenBundle/issues/255#issuecomment-1030286770
[2]: https://github.com/markitosgv/JWTRefreshTokenBundle/pull/303

**Comment by AimSai59** [comment]
after a LOT of debugging, I found that the solution is to simply add `check_path: gesdinet_jwt_refresh_token` in the security.yaml, like this:
`refresh:
            // ...
            refresh_jwt: 
                check_path: gesdinet_jwt_refresh_token`

**Comment by youassi** [comment]
For Symfony 6. 0 +

`   firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login$
            provider: app_user_provider
            stateless: true
            json_login:
                check_path: /api/login # or api_login_check as defined in config/routes.yaml
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh_jwt:
            refresh_jwt:
                check_path: /api/token/refresh
            provider:  app_user_provider
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: jwt`

**Comment by youassi** [comment]
`
   firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login$
            provider: app_user_provider
            stateless: true
            json_login:
                check_path: /api/login # or api_login_check as defined in config/routes.yaml
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh_jwt:
            refresh_jwt:
                check_path: /api/token/refresh
            provider:  app_user_provider
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: jwt
`

**Comment by youassi** [comment]
Work well with configuration : 

        refresh_jwt:
            refresh_jwt:
                check_path: /api/token/refresh
            provider:  app_user_provider

**Comment by irmantas** [comment]
If anyone have route issues configuring this with SF 6.1, here is my solution:
Add users provider to refresh firewall, configure new route with different path than `/api/token/refresh`. For example:
```yaml
# security.yaml
    firewalls:
        # ...
        refresh:
            provider: my_user_provider
            refresh_jwt:
                check_path: api_refresh_token
```

```yaml
# routes.yaml
api_refresh_token:
    path: /api/token/renew
```

**Comment by mouataz1** [comment]
hello, 
i dont know if u still need the solution , any way this ts my configuration and it works jut fine :
symfony 6.2
on the routes.yaml file : 

api_refresh_token:
    path: /api/token/refresh

on the security.yaml file this is my firewall : 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: /logout
        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/token/refresh
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        main:
            custom_authenticators:
                - App\Security\MyGoogleAuthenticator
                - App\Security\MyLinkedinAuthenticator
            entry_point: App\Security\MyGoogleAuthenticator

also do not forget to add the  access control :
- { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }

**Comment by SergeMezui16** [comment]
Hi !

I recently had the same problem with Symfony 6.2 and PHP 8.1.

Fortunately, I got the solution.

It seems that the refresh route has been configured to accept only some pattern of url.
I test some url for this route and the controller was not the problem. The problem came from the path of our routes.
By the look of it, routes path like `/auth/refresh/token` are bad where routes path like  `api/refresh/token` (whith is recommended by the bundle in doc), `refresh/token` or `token/refresh` are good !

I don't take more time to test which path occur an error or not but I think the problem is that the bundle auto configure some routes path and not others.

That is my configuration :

```yaml
# route.yaml
# ...
api_refresh_token:
    path: /token/refresh
    methods: [POST]
# ...
``` 

```yaml
# security.yaml
security:
# ...
    firewalls:
    # ...
        api_token_refresh:
            pattern: /token/refresh
            stateless: true
            provider: app_user_provider # provider in database
            refresh_jwt:
                check_path: api_refresh_token
    # ...
# ...
    access_control:
        # ...
        - { path: ^/token/refresh$, roles: PUBLIC_ACCESS }
        # ...
# ...
``` 

I have removed the path configuration in `gesdinet_jwt_refresh_token.yaml`, with this configuration it will not work again. I recommend you to remove this file because it isn't helpful anymore.
Then, my configuration is like this : 
```yaml
# gesdinet_jwt_refresh_token:
    # path: /token/refresh
# ...
``` 
Now, it works so good !
So. That solution is just temporary, I guest they will fix it.
I wish I helped you. 👍🏾

**Comment by maximanek** [comment]
Hello i've done my configuration like @SergeMezui16. And its working just fine, but when I add prefix /api/ to match rest of my app i still got wrongly configured route exception

**Comment by EnterVPL** [comment]
@SergeMezui16  Very very thanks! ❤️  Your solution works! 😀 
> Hi !
> 
> I recently had the same problem with Symfony 6.2 and PHP 8.1.
> 
> Fortunately, I got the solution.
> 
> It seems that the refresh route has been configured to accept only some pattern of url. I test some url for this route and the controller was not the problem. The problem came from the path of our routes. By the look of it, routes path like `/auth/refresh/token` are bad where routes path like `api/refresh/token` (whith is recommended by the bundle in doc), `refresh/token` or `token/refresh` are good !
> 
> I don't take more time to test which path occur an error or not but I think the problem is that the bundle auto configure some routes path and not others.
> 
> That is my configuration :
> 
> ```yaml
> # route.yaml
> # ...
> api_refresh_token:
>     path: /token/refresh
>     methods: [POST]
> # ...
> ```
> 
> ```yaml
> # security.yaml
> security:
> # ...
>     firewalls:
>     # ...
>         api_token_refresh:
>             pattern: /token/refresh
>             stateless: true
>             provider: app_user_provider # provider in database
>             refresh_jwt:
>                 check_path: api_refresh_token
>     # ...
> # ...
>     access_control:
>         # ...
>         - { path: ^/token/refresh$, roles: PUBLIC_ACCESS }
>         # ...
> # ...
> ```
> 
> I have removed the path configuration in `config/routes/gesdinet_jwt_refresh_token.yaml` created by Symfony Recipes, with this configuration it will not work again. I recommend you to remove this file because it isn't helpful anymore. Then, my configuration is like this :
> 
> ```yaml
> # gesdinet_jwt_refresh_token:
>     # path: /token/refresh
> # ...
> ```
> 
> Now, it works so good ! So. That solution is just temporary, I guest they will fix it. I wish I helped you. 👍🏾

**Comment by Servialux** [comment]
> Work well with configuration :
> 
> ```
>     refresh_jwt:
>         refresh_jwt:
>             check_path: /api/token/refresh
>         provider:  app_user_provider
> ```

@youassi  Thanks a lot work for me

**Comment by Inscure** [comment]
Hello, when this will be officially fixed?

**Comment by SergeMezui16** [comment]
> Hello, when will this be officially fixed?
I don't if they really consider that it has been to be fixed!

**Comment by bobas01** [comment]
hi everywone, i try all youre solution for to have the same result when i want to migrate :
 Unrecognized options "secret, lifetime, path" under "security.firewalls.remember_me". Available options are "access_denied_handler", "access_denied_url", "access_token", "context", "custom_authenticators   
  ", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "jwt", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern   
  ", "provider", "refresh_jwt", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509".  
  
   If someone have an idea thks

**Comment by SergeMezui16** [comment]
> hi everywone, i try all youre solution for to have the same result when i want to migrate : Unrecognized options "secret, lifetime, path" under "security.firewalls.remember_me". Available options are "access_denied_handler", "access_denied_url", "access_token", "context", "custom_authenticators ", "entry_point", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "jwt", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern ", "provider", "refresh_jwt", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509".
> 
> If someone have an idea thks

Can you share your entire configuraion ? security.yaml and route.yaml ?

**Comment by bobas01** [comment]
yes:
`security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    jwt:
      lexik_jwt:
        class: App\Entity\User
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login # or api_login_check as defined in config/routes.yaml
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      provider: app_user_provider

    api:
      pattern: ^/api
      stateless: true
      provider: jwt
      jwt: ~

      # main:
      #   lazy: true
      #   provider: app_user_provider
      #   json_login:
      #     check_path: api_login
      #     success_handler:
      # logout:
      #   path: api_logout
      # custom_authenticator: App\Security\AppAuthenticator
      # where to redirect after logout
      # target: app_any_route

    remember_me:
      secret: "%kernel.secret%"
      lifetime: 604800
      path:
        /
        # by default, the feature is enabled by checking a checkbox in the
        # login form, uncomment the following line to always enable it.
        #always_remember_me: true

    # activate different ways to authenticate
    # https://symfony.com/doc/current/security.html#the-firewall

    # https://symfony.com/doc/current/security/impersonating_user.html
    # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
`

**Comment by SergeMezui16** [comment]
You shouldn't put your remember_me configuration at the same level with firewalls but under a specific firewall as said in symfony doc

**Comment by SergeMezui16** [comment]
@bobas01 You shouldn't put your remember_me configuration at the same level with firewalls but under a specific firewall as said in symfony doc;

**Comment by bobas01** [comment]
@SergeMezui16  thks dude it's working un put with api but i don't know if is the good one. But i don't have error

**Comment by SergeMezui16** [comment]
@bobas01  You shouldn't put your remember_me configuration at the same level with firewalls but under a specific firewall as said in  [symfony doc.](https://symfony.com/doc/current/security/remember_me.html#remember-me-for-json-login)

Your ```security.yaml``` configuration should look like this: 

```yaml
# security.yaml
security:
    # ....

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        jwt:
            lexik_jwt:
            class: App\Entity\User


    firewalls:
    #...
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
          

         api:
             pattern: ^/api
             stateless: true
             provider: jwt
             jwt: ~
             # Delete all cookies on logout
             logout:
                 path: api_token_invalidate
                 delete_cookies:
                     refresh_token:
                         path: /
                         samesite: none
                     token:
                         path: /
                         samesite: none
       
            # if you use jwt refresh token
            api_token_refresh:
                pattern: ^/token/refresh$
                stateless: true
                provider: app_user_provider
                user_checker: App\Security\UserChecker
                refresh_jwt:
                     check_path: api_refresh_token

            main:
                lazy: true
                provider: app_user_provider
                stateless: true
                remember_me:
                    secret: "%kernel.secret%"
                    lifetime: 604800

# ...
```

And your ```route.yaml``` : 

```yaml
# route.yaml
# ...
api_refresh_token:
    path: /token/refresh
    methods: [POST]
# ...
```

**Comment by bobas01** [comment]
@SergeMezui16 i try your code and i come back with th same error
In ArrayNode.php line 327:

  Unrecognized option "api_token_refresh" under "security.firewalls.api". Available options are "access_denied_handler", "access_denied_url", "access_token", "context", "custom_authenticators", "entry_poin  
  t", "form_login", "form_login_ldap", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "jwt", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "provider",  
   "refresh_jwt", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509".

**Comment by SergeMezui16** [comment]
@bobas01 My bad. I put ```main``` and ```api_token_refresh``` firewalls at the same level 👎🏾 ! You can try this again i change it ;)!

**Comment by bobas01** [comment]
@SergeMezui16  yes it's change but i've a new problem :
In ArrayNode.php line 327:
                                                                                                                                             
  Unrecognized option "class" under "security.providers.jwt". Available options are "chain", "entity", "id", "ldap", "lexik_jwt", "memory".
  
  If you want i've discord bobas01

**Comment by ozahorulia** [comment]
For those who is facing a similar problem, check if any other firewall doesn't override your refresh firewall. E.g. I had this config before updating to 5.4 style:

```
        api_auth:
            pattern: ^(\/[a-z]{2})?/api/token/(refresh|verify)
            stateless: false
        api_refresh:
            pattern: ^(\/[a-z]{2})?/api/token/refresh
            stateless: false
            provider: database_users
            refresh_jwt:
                check_path: gesdinet_jwt_refresh_token
```

I was struggling for hours until I noticed that `api_auth` firewall matched the refresh path, thus api_refresh firewall didn't work at all. So silly mistake but I suppose someone may doing same mistake without realizing it :)

**Comment by mohammad-salehe-alizadegan** [comment]
Hello all developers i had same issue but i resolve it.
all of configs were similar to each other and those labels are not important at all.
As you know after symfony 5 this bundle controller has deprecated and it’s not useable so you should define your config like below
In config/packages/secutiry.yaml

`  
security:
    api:
        refresh_jwt:
        check_path: refresh_jwt
        provider: app_user_provider
    access_control:
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
`
Now in your config/route.yaml

`
refresh_jwt:
    path: /api/token/refresh
`
Now

**### also Pay attention** 
It's time to define app_user_provider if you didn’t have any user provider and you didnt developed it.

`
<?php


namespace App\Security;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UserNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

class UserProvider implements UserProviderInterface
{
    private UserRepository $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * Symfony calls this method if you use features like switch_user
     * or remember_me.
     *
     * If you're not using these features, you do not need to implement
     * this method.
     *
     * @throws UnsupportedUserException if the account is not supported
     */
    public function refreshUser(UserInterface $user): UserInterface
    {
        if (!$user instanceof User) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', $user::class));
        }

        return $this->loadUserByIdentifier($user->getUserIdentifier());
    }

    /**
     * Whether this provider supports the given user class.
     *
     * @param string $class
     * @return bool
     */
    public function supportsClass(string $class): bool
    {
        return User::class === $class || is_subclass_of($class, User::class);
    }

    /**
     * @param string $identifier
     * @return UserInterface
     */
    public function loadUserByIdentifier(string $identifier): UserInterface
    {
        if (is_numeric($identifier)){
            $user = $this->userRepository->find($identifier); // Use the correct field (username, email, etc.)
        }
        else{
            $user = $this->userRepository->findOneBy(['username'=>$identifier]); // Use the correct field (username, email, etc.)
        }

        if (null === $user) {
            throw new UserNotFoundException(sprintf('User "%s" not found.', $identifier));
        }

        return $user;
    }

}

`

Also if you got error regarding to RefreshToken Entity it might be you should define repository for Entity like others

`#[ORM\Entity(repositoryClass: RefreshTokenRepository::class)]`

**Comment by mohammad-salehe-alizadegan** [comment]
@Bohilc if you had any other question you can ask here.

**Comment by shakaran** [comment]
@AimSai59 got it, and so did @irmantas and @youassi from the other direction: the fix is `check_path`. Worth writing out why, because two different causes have produced this same error over the years and the thread has both of them in it.

**The one that applies now.** `check_path` decides which requests the authenticator takes over, and it defaults to `/login_check` — Lexik's *login* path, which makes no sense for refreshing but is where the default came from. So `refresh_jwt: ~` leaves your refresh route unanswered. The request carries on to the router, which finds the route you defined and nothing behind it, and reports the route as wrongly configured. The route is fine. The message names the wrong thing.

```yaml
security:
    firewalls:
        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            provider: app_user_provider
            refresh_jwt:
                check_path: /api/token/refresh # or the route name
```

@mv-developer's `provider` is worth having too, but on its own it was never going to fix this, which is why @matmkian, @DougHayward, @gregurco and @andrconstruction all reported it still failing.

I reproduced this on a current Symfony while closing #330. With `refresh_jwt: ~` the log says it outright — `Authenticator does not support the request`, then `Unable to look for the controller as the "_controller" parameter is missing` — and setting `check_path` makes the authenticator take the request. It is documented as of dbc4853, both in the README and as an `info()` on the node so it shows in `config:dump-reference`.

**The other cause, for anyone reading the thread's history.** @Jayfrown was right about a real and different problem: before 1.1, `supports()` reported support based on whether the refresh token was in the request, so a request without one fell through to the router and produced this same 404. #303 changed it to path checking (1c1abc8), released in v1.1.0. Two causes, one error message, which is why the thread reads as if the answers contradict each other. They do not — they are from either side of that change.

**Do not use that workaround now.** @Jayfrown said to remove it when a release landed, and that advice has aged into a trap:

```yaml
controller: gesdinet.jwtrefreshtoken::refresh # removed in 2.0
```

That controller no longer exists, so it fails differently. The route needs no controller at all — the firewall answers the path before a controller would be reached.

Closing this as a duplicate of #330, now documented.
