### ISSUE TITLE
Expand Refresh Token TTL on every calls

### ISSUE THREAD

**Issue by Seb33300** [gesdinet/JWTRefreshTokenBundle#44]
Hi,

I would like the user session expire XXX minutes after the last action on the application by the user.

If I understand correctly, `ttl_update: true` seems to expend the refresh token ttl only when we call the `token/refresh` service?

Is it possible to expend the refresh token ttl automatically on every call of any webservices?

Thanks

Seb

**Comment by Seb33300** [comment]
Maybe we can do it by putting a refresh on a LexikJWTAuthenticationBundle event on authenticate?

**Comment by lolmx** [comment]
> Is it possible to expend the refresh token ttl automatically on every call of any webservices?

Reading this, I think the best way to achieve this is by implementing your own RequestListener. It should not be handled by the bundle.

You may try:

```
<?php

namespace Your\Namespace;

use Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;

/**
 * Class RequestListener
 * @package Your\Namespace
 */
class RequestListener
{
    private $refreshTokenService;

    /**
     * RequestListener constructor.
     * @param RefreshToken $refreshTokenService
     */
    public function __construct(RefreshToken $refreshTokenService)
    {
        $this->refreshTokenService = $refreshTokenService;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();

        $this->refreshTokenService->refresh($request);
    }
}
```

```
my_app.request_listener:
        class: "%my_app.request_listener.class%"
        arguments: [ '@gesdinet.jwtrefreshtoken' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```

I didn't try but I think it should work. Hope it'll help you.
