### ISSUE TITLE
refresh token with additional fields in payload

### ISSUE THREAD

**Issue by nicraMarcin** [gesdinet/JWTRefreshTokenBundle#65]
Hello,
I'm new in symfony and and try to set HWTRefreshTokenBundle with JTW Lexik. 
In jwt I have own Entity
```
namespace SharedBundle\Security;

final class User implements \Lexik\Bundle\JWTAuthenticationBundle\Security\User\JWTUserInterface
{
    private $username;
    private $roles;
    private $name;
    
    public function __construct($username, array $roles, $email, $name)
    {
        $this->username = $username;
        $this->roles = $roles;
        $this->email = $email;
        $this->name = $name;
    }
    
    public static function createFromPayload($username, array $payload)
    {
        return new self(
            $username,
            $payload['roles'], // Added by default
            $payload['email'],  // Custom
            $payload['name']
        );
    }

 /**
     * {@inheritdoc}
     */
    public function getUsername()
    {
        return $this->username;
    }
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * {@inheritdoc}
     */
    public function getRoles()
    {
        return $this->roles;
    }
 ...
```
In listener I add custom data:
```
public function onJWTCreated(JWTCreatedEvent $event) {
    $request = $this->requestStack->getCurrentRequest();

    $payload = $event->getData();
    $user = $event->getUser();
    
    $payload['name'] = $user->getName();
    $payload['email'] = $user->getEmail();
    $payload['ip'] = $request->getClientIp();

    $event->setData($payload);
  }
```
But when I try to refresh token I get error:
```
[Mon May 29 22:07:36 2017] 127.0.0.1:56078 [200]: /api/token/refresh
[Mon May 29 22:13:52 2017] PHP Fatal error:  Call to undefined method Symfony\Component\Security\Core\User\User::getName() in .../application/be/src/SharedBundle/EventListener/JWTCreatedListener.php on line 33
Segmentation fault
```
When I throw email and name from payload token is created but without this data, and return only default role `ROLE_USER` without `ROLE_ADMIN`.

I'tried to use `refresh_token_entity: SharedBundle\Security\User`  but without result :/
How can I implemet additional fields in payload?

**Comment by thecassion** [comment]
I have the same problem like you. How did you handle it @nicraMarcin ? This issue still exist. Did you use an other bundle or customize this one?

**Comment by thecassion** [comment]
Ok . Thanks I understand . For me I don't use FOSRestBundle . I only use Api-platform . I will try to refresh token with my own logic like you do. Thanks again

**Comment by remoteclient** [comment]
I use this with Api Platform and it works. I use another Event I think:
```php
use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent;
use MWS\UserBundle\Model\UserInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class JWTAuthenticatedListener
{
    /**
     * @var TokenStorageInterface
     */
    private $tokenStorage;

    /**
     * @param TokenStorageInterface $tokenStorage
     */
    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    /**
     *
     * @param AuthenticationSuccessEvent $event
     * @return void
     */
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $user = $event->getUser();

        if (!$user instanceof UserInterface) {
            return;
        }
        $data = $event->getData();
        $data['id'] = $user->getId();

        $event->setData($data);
    }
}
```

**Comment by wittyweb** [comment]
I also use it with api-platform and had the same problem with the onJWTCreated event.
I found a solution to still be able to pass some data in the onJWTCreated listener. If the method I have to use doesn't exist, I manually load the user thanks to the entityManager. I don't know if it is a completely clean solution but it works :

```
public function onJWTCreated(JWTCreatedEvent $event): void
    {
        /* @var $user User|UserInterface */
        $user = $event->getUser();

        // If user comes from refresh token, we don't have the id and is Active properties
        if (!method_exists($user, 'getId')) {
            $user = $this->entityManager->getRepository(User::class)->findOneBy([
                'email' => $user->getUsername()
            ]);
        }

        $payload = $event->getData();
        $payload['id'] = $user->getId();
        $payload['isActive'] = $user->getIsActive();

        $event->setData($payload);
    }
```

**Comment by roelbeerens** [comment]
@wittyweb You saved me there! Thanks!

**Comment by peterforeman** [comment]
@jspizziri This should be in the docs! Thanks!

**Comment by steveKac01** [comment]
> 



> FWIW, I was also having an issue with the JWT generated after refresh. My issue was that on login, the JWT would contain the complete set of User roles, but on refresh, it wouldn't. The fix was simply to specify the `user_provider` in gesdinet config to be the same as the one used during initial authentication (in my case an `fos_user.user_provider`:

Hello, I have the same issue but i'm not using custom provider; can you help me please ? I'mmmm so stuck :')

**Comment by jspizziri** [comment]
@steveKac01 i haven't used symfony in several years. Good luck!

**Comment by GregDevLab** [comment]
@jspizziri @steveKac01 this is my first participation, I hope to help you 😉
[JWTRefreshTokenBundle](https://github.com/markitosgv/JWTRefreshTokenBundle#set-the-user-provider) <== it works for me

```YAML
 # config/packages/security.yaml
    app_user_provider: # the provider i use for refresh token
      entity:
        class: App\Entity\User
        property: username
    jwt:
      lexik_jwt:
        class: App\Security\UserAuthenticate
  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    login:
      # some config
    api:
      pattern: ^/api/
      stateless: true
      entry_point: jwt
      provider: jwt
      jwt: ~
      refresh_jwt:
        check_path: /api/token/refresh
        provider: app_user_provider # the user's provider must be declared here
```

```YAML
# config/packages/gesdinet_jwt_refresh_token.yaml (automatically create from JWTRefreshTokenBundle recipes)
gesdinet_jwt_refresh_token:
  refresh_token_class:   @@App\Entity\RefreshToken
```
