### ISSUE TITLE
Events to Customize Response Data?

### ISSUE THREAD

**Issue by becauseinterwebs** [gesdinet/JWTRefreshTokenBundle#67]
In Lexik you can customize the data response using event listeners.  The way the refresh token is added breaks our REST API model and I need to be able to customize the response as I can with Lexik.  Are there events I can subscribe to in order to make sure the refresh token is placed in the right part of the response instead of just appended to it?

Thank you!

**Comment by Nightbr** [comment]
Hello,

use `php bin/console debug:event-dispatcher` to debug and plug your eventListener after `Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener::attachRefreshToken()`

Such as:

_The event class src/UserBundle/EventListener/AuthenticationSuccessListener.php_
``` PHP
<?php

namespace UserBundle\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent;
use FOS\UserBundle\Model\UserInterface;

class AuthenticationSuccessListener
{
    private $jwtTokenTtl;

    public function __construct($jwtTokenTtl)
    {
        $this->jwtTokenTtl = $jwtTokenTtl;
    }

    /**
     * @param AuthenticationSuccessEvent $event
     */
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $data = $event->getData();
        $user = $event->getUser();

        if (!$user instanceof UserInterface) {
            return;
        }

        $formattedData = array(
            'AccessToken' => $data['token'],
            'RefreshToken' => $data['refresh_token'],
            'TokenType' => "Bearer",
            'ExpiresIn' =>$this->jwtTokenTtl
        );

        $event->setData($formattedData);
    }
}
```


Register the event
_UserBundle\Resources\config\services.yml_
``` YAML
services:
    user.jwt.authentification.success.listener:
        class: UserBundle\EventListener\AuthenticationSuccessListener
        arguments: ["%jwt_token_ttl%"]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, priority: -1, method: onAuthenticationSuccessResponse }
        autoconfigure: false
```

Debug with `php bin/console debug:event-dispatcher`:

![image](https://user-images.githubusercontent.com/4228646/31771446-75540124-b4dc-11e7-953e-0fc4562dbc70.png)

Let me know if it works for you!
