### ISSUE TITLE
Possible to Use Chained User Provider ?

### ISSUE THREAD

**Issue by silverbackdan** [gesdinet/JWTRefreshTokenBundle#68]
Is it possible to use a chained user provider? E.g. A couple of default users in memory and some from FosUserBundle ?

Not a huge deal as I can just load those in as fixtures, but I was just curious because the user provider needs to be defined as a service ID it seems.

**Comment by vpassapera** [comment]
Same question. Seems to throw error when using chain.

**Comment by vpassapera** [comment]
Think i found a solution... inspecting the container i see that chain providers are aliased to:

security.user.provider.concrete.<your_id_here> which then seems to be picked up by the CompilerPass accordingly.

**Comment by shubaivan** [comment]
I added 

```
gesdinet_jwt_refresh_token:
    ttl: '%jwt_refresh_token_ttl%'
    ttl_update: true
    user_provider: security.user.provider.concrete.chain_provider
```
