### ISSUE TITLE
Does not support multiple custom providers for SF4

### ISSUE THREAD

**Issue by rimvislt** [gesdinet/JWTRefreshTokenBundle#97]
Can we implement multiple-custom providers support for this bundle? 

something like
````
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
            provider: custom_admin

        refresh:
            pattern:  ^/api/client/token/refresh
            stateless: true
            anonymous: true
            provider: custom_client

        refresh:
            pattern:  ^/api/supplier/token/refresh
            stateless: true
            anonymous: true
            provider: custom_supplier
````
solved by using chain provider in config 
user_provider: security.user.provider.concrete.chain_provider
