### ISSUE TITLE
How to generate APIDOC with Symfony4 for the refresh token route ?

### ISSUE THREAD

**Issue by vincent-dravert** [gesdinet/JWTRefreshTokenBundle#98]
Hi,

Is there anyway to have a proxy action in my controller to add the annotation in order to get the refresh endpoint documented on my APIDOC ?

I am using PHP7.1 / Symfony 4.0

Thanks
Vincent

**Comment by Kolvin** [comment]
@vincent-dravert did you ever get a workaround? finding myself needing to do the same

**Comment by aidarkolbaev** [comment]
@Kolvin 
I found a solution

just extend **Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken** class
full code below (or [here](https://gist.github.com/aidarkolbaev/ab5ac5aca032e90b59323261a2ac2e16)):

```yaml
# config/services.yaml
services:
    # other settings
    ...

    App\Controller\RefreshTokenHandler:
        arguments:
            - "@gesdinet.jwtrefreshtoken.authenticator"
            - "@gesdinet.jwtrefreshtoken.user_provider"
            - "@lexik_jwt_authentication.handler.authentication_success"
            - "@lexik_jwt_authentication.handler.authentication_failure"
            - "@gesdinet.jwtrefreshtoken.refresh_token_manager"
            - "%gesdinet_jwt_refresh_token.ttl%"
            - "%gesdinet_jwt_refresh_token.security.firewall%"
            - "%gesdinet_jwt_refresh_token.ttl_update%"
            - "@event_dispatcher"
        tags: ['controller.service_arguments']
```

```php
<?php
// src/Controller/RefreshTokenHandler.php

namespace App\Controller;

use Gesdinet\JWTRefreshTokenBundle\Model\RefreshTokenManagerInterface;
use Gesdinet\JWTRefreshTokenBundle\Security\Authenticator\RefreshTokenAuthenticator;
use Gesdinet\JWTRefreshTokenBundle\Security\Provider\RefreshTokenProvider;
use Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface;
use OpenApi\Annotations as OA;

class RefreshTokenHandler extends RefreshToken
{
    /**
     * RefreshTokenHandler constructor.
     * @param RefreshTokenAuthenticator $authenticator
     * @param RefreshTokenProvider $provider
     * @param AuthenticationSuccessHandlerInterface $successHandler
     * @param AuthenticationFailureHandlerInterface $failureHandler
     * @param RefreshTokenManagerInterface $refreshTokenManager
     * @param $ttl
     * @param $providerKey
     * @param $ttlUpdate
     * @param EventDispatcherInterface $eventDispatcher
     */
    public function __construct(
        RefreshTokenAuthenticator $authenticator,
        RefreshTokenProvider $provider,
        AuthenticationSuccessHandlerInterface $successHandler,
        AuthenticationFailureHandlerInterface $failureHandler,
        RefreshTokenManagerInterface $refreshTokenManager,
        $ttl,
        $providerKey,
        $ttlUpdate,
        EventDispatcherInterface $eventDispatcher)

    {
        parent::__construct($authenticator, $provider, $successHandler, $failureHandler, $refreshTokenManager, $ttl, $providerKey, $ttlUpdate, $eventDispatcher);
    }

    /**
     * @OA\Response(
     *     response="200",
     *     description="Returns new tokens",
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="access_token", type="string"),
     *         @OA\Property(property="refresh_token", type="string")
     *     )
     * )
     *
     * @OA\Response(
     *     response="401",
     *     description="Invalid token",
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="code", type="integer", example="401"),
     *         @OA\Property(property="message", type="string")
     *     )
     * )
     *
     * @OA\RequestBody(
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="refresh_token", type="string"),
     *     )
     * )
     *
     * @OA\Tag(name="users")
     *
     *
     *
     * @param Request $request
     * @return mixed
     */
    public function refresh(Request $request)
    {
        return parent::refresh($request);
    }
}
```

**Comment by codeclipse** [comment]
Works great.

You can even avoid overwriting constructor and passing arguments by using parent dependency.
Additionally you can set up route using annotation this way.

```yaml
# services.yml

services:

    # ...

    App\Controller\RefreshTokenController:
        parent: gesdinet.jwtrefreshtoken

```

```php
<?php
// src/Controller/RefreshTokenHandler.php

namespace App\Controller;

use Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken;
use OpenApi\Annotations as OA;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RefreshTokenHandler extends RefreshToken
{
    /**
     * @Route(
     *     "/api/token/refresh",
     *     methods={ "POST" },
     * )
     *
     * @OA\Response(
     *     response="200",
     *     description="Returns new tokens",
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="access_token", type="string"),
     *         @OA\Property(property="refresh_token", type="string")
     *     )
     * )
     *
     * @OA\Response(
     *     response="401",
     *     description="Invalid token",
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="code", type="integer", example="401"),
     *         @OA\Property(property="message", type="string")
     *     )
     * )
     *
     * @OA\RequestBody(
     *     @OA\JsonContent(
     *         type="object",
     *         @OA\Property(property="refresh_token", type="string"),
     *     )
     * )
     *
     * @OA\Tag(name="users")
     */
    public function refresh(Request $request): Response
    {
        return parent::refresh($request);
    }
}
```

**Comment by shakaran** [comment]
@vincent-dravert, @kolvin — seven years on, there is a proper answer for one of the two documentation tools, and a straightforward one for the other.

**@aidarkolbaev's workaround no longer applies.** All three classes it extends and injects — `Service\RefreshToken`, `Security\Authenticator\RefreshTokenAuthenticator` and `Security\Provider\RefreshTokenProvider` — were removed in 2.0. The refresh endpoint is a firewall authenticator now, so there is no service to wrap in a controller and hang annotations off. It was a good workaround while there was.

**If you use API Platform**, this is built in as of #372:

```yaml
gesdinet_jwt_refresh_token:
    api_platform:
        enabled: true
```

That documents the refresh endpoint in the generated OpenAPI specification, and adds `refresh_token` to the login response schema, which Lexik's own integration leaves out. It reads the bundle's configuration, so the request body, the response and the cookie case all follow what you actually configured rather than being written out by hand.

**If you use NelmioApiDocBundle**, there is no controller to annotate and there will not be one. Describe the path directly, which Nelmio merges into its output:

```yaml
nelmio_api_doc:
    documentation:
        paths:
            /api/token/refresh:
                post:
                    tags: [Authentication]
                    summary: Exchanges a refresh token for a new JWT.
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        refresh_token: { type: string }
                                    required: [refresh_token]
                    responses:
                        200:
                            description: JWT refreshed
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token: { type: string }
                                            refresh_token: { type: string }
                        401:
                            description: The refresh token is missing, unknown or has expired
```

Less satisfying than the API Platform route, since it is written by hand and can drift from your configuration — worth remembering if you turn on the cookie with `remove_token_from_body`, at which point there is no `refresh_token` in the response to document.

Closing this. The proxy controller you asked about is neither possible nor needed now.
